### ISSUE TITLE
Erro ao Subir servidor 

### ISSUE THREAD

**Issue by lanacruz** [glaucia86/hands-on-bots-node#5]
ao Tentar subir o Servidor apresenta um erro. Cheguei a copiar seu codigo para ver se era erro do meu e continuou. 
erro:

[nodemon] 1.18.4
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node saudacao.js`
module.js:549
    throw err;
    ^

Error: Cannot find module 'restify'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\_TCCBot\src\Modulo-3\saudacao.js:6:17)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by glaucia86** [comment]
Você deu npm install na mesma raiz onde se encontra o arquivo 'package.json'?
Caso o problema persiste me avise que entro na sua máquina para ver o que está acontecendo.
